# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Test

on:
  push:
  pull_request:

jobs:
  swift:
    name: Swift
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Test
        run: swift test
  iOS:
    name: Test iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: xcodebuild -scheme QSChatView test -destination "platform=iOS Simulator,name=iPhone 14 Pro,OS=latest" | xcpretty
  macOS:
    name: Test macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: xcodebuild -scheme QSChatView test -destination "platform=macOS" | xcpretty
  macOS_Catalyst:
    name: Test macOS (Catalyst)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: xcodebuild -scheme QSChatView test -destination "platform=macOS,variant=Mac Catalyst" | xcpretty
